#!/bin/bash

project_name=
project_description=
project_author=
state_manager=
folders_organization=
project_type=
git_setup=    # true or false
fvm_setup=    # true or false
flutter_version=     # all fvm possible versions (master, stable, alpha, beta, 2.7.0, 2.12.0, etc..)

## All possible licenses:
#  GNU GPLv3
#  GNU LGPLv3
#  Mozilla Public License 2.0
#  Apache License 2.0
#  MIT License
#
project_license=
